# Generated by Django 5.2.4 on 2025-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
