# Generated by Django 5.2.4 on 2025-07-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_system",
            "0009_remove_user_daily_received_remove_user_daily_sent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SendEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="daily_received",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="daily_sent",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="last_limit_reset",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
