# Generated by Django 5.2.4 on 2025-07-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0010_sendemail_remove_user_nickname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
