# Generated by Django 5.2.4 on 2025-07-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0011_delete_sendemail_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
