# Generated by Django 5.2.4 on 2025-07-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('local_gov', models.CharField(blank=True, max_length=100, null=True, verbose_name='LGA')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark')),
                ('user_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier 1', 'Tier 1'), ('tier 2', 'Tier 2'), ('tier 3', 'Tier 3')], default='Tier 1', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('monnify_account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('monnify_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
