# Generated by Django 5.2.4 on 2025-07-11 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('local_gov', models.CharField(blank=True, max_length=100, null=True, verbose_name='LGA')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark')),
                ('user_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
