# Generated by Django 5.2.4 on 2025-07-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
