# Generated by Django 5.2.4 on 2025-07-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="recipient_daily_received",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_daily_sent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
