# Generated by Django 5.2.4 on 2025-07-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_transaction_recipient_daily_received_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="recipient_daily_received",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sender_daily_sent",
        ),
    ]
