# Generated by Django 5.2.4 on 2025-07-14 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_transaction_recipient_daily_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('daily_inflow', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('daily_outflow', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TierUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.CharField(choices=[('tier 1', 'Tier 1'), ('tier 2', 'Tier 2'), ('tier 3', 'Tier 3')], max_length=10)),
                ('requested_tier', models.CharField(choices=[('tier 1', 'Tier 1'), ('tier 2', 'Tier 2'), ('tier 3', 'Tier 3')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('nin', 'NIN Slip'), ('voter_card', "Voter's Card"), ('driver_license', "Driver's License"), ('passport', 'International Passport')], max_length=20, null=True)),
                ('id_document', models.URLField(blank=True, max_length=1000, null=True)),
                ('utility_bill', models.URLField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
