# Generated by Django 5.2.4 on 2025-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_transaction_fee_alter_walletfunding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10),
        ),
        migrations.DeleteModel(
            name='WalletFunding',
        ),
    ]
