# Generated by Django 5.2.4 on 2025-07-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_transaction_transaction_type_delete_walletfunding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sender',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
    ]
