# Generated by Django 5.2.4 on 2025-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_rename_sender_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_account_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
